export const TO_DO_ITEMS_FETCH_LOADING = 'TO_DO_ITEMS_FETCH_LOADING';
export const TO_DO_ITEMS_FETCH_LOADED = 'TO_DO_ITEMS_FETCH_LOADED';
export const TO_DO_ITEMS_FETCH_ERROR = 'TO_DO_ITEMS_FETCH_ERROR';
export const TO_DO_ITEMS_ADD_NEW = 'TO_DO_ITEMS_ADD_NEW';
export const TO_DO_ITEMS_ADD_NEW_SENDING = 'TO_DO_ITEMS_ADD_NEW_SENDING';
export const TO_DO_ITEMS_ADD_NEW_SENDED = 'TO_DO_ITEMS_ADD_NEW_SENDED';
export const TO_DO_ITEMS_ADD_NEW_ERROR = 'TO_DO_ITEMS_ADD_NEW_ERROR';
